---
title: "Bayesian Intensity Modeling"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false


# load libraries
library(ggplot2)
library(ggridges)
library(ggforce)

library(tidyverse)
library(purrr)

library(tidybayes)
library(brms)

library(here)

library(rcarbon)
library(c14bazAAR)

library(sf)
library(terra)
library(rnaturalearth)
library(rnaturalearthdata)

library(cmdstanr)
library(posterior)
library(bayesplot)


library(dbscan)
library(factoextra)

library(akima)

require(doSNOW)
require(doParallel)
require(doRNG)
```

```{r}
seed = 1
set.seed(1)
# Load data from southern African database

# set directory
dir = here::here()

# read in and modify data names and assign as date list for c14bazAAR
c14_za <- read_csv(paste0(dir, "/data/SARD_Mar2021_14C.csv")) |>
  rename(c14age = Date, c14std = Uncertainty,  labnr = 'Lab ID',
         lon = DecdegE, lat = DecdegS,
         material = 'Material dated', species = Species) |>
  as.c14_date_list()

# load the SASSI database for full ZA site locations
sassi <- read_csv(paste0(dir, '/data/SASSI_v3.2_S1.csv')) |>
  pivot_longer('ESA':'CeramicLSA', names_to = 'Industry', 
               values_to = 'Presence') |>
  mutate(Presence = ifelse(!is.na(Presence), 1, 0)) |>
  filter((Industry %in% c('LSA', 'GenLSA', 'Robberg', 'Oakhurst', 
                         'Wilton', 'FinalLSA', 'CeramicLSA')) &
           (Presence == 1))


```

```{r}
# filter by late pleistocene
max_age <- 21000 
min_age <- 2000
temp_res <- 100

#filter to remove human remains as they produce errors when calibrating
za <- c14_za |>
  filter(species != "Homo sapiens" | is.na(species)) |>
  
  # filter by dates older than 200 years and less than 50 ka
  filter(c14age > min_age, c14age < max_age)


# filter by terrestrial material and apply the terrestrial calibration curve
za_terr <- za |>
  filter(!material %in% c('Marine shell', 'marine shell',
                          'marine other', 'iron')) |>
  drop_na(c14age, c14std)

za_terr_cal <- rcarbon::calibrate(za_terr$c14age , za_terr$c14std,
                                      calCurves = 'shcal20',
                                      ids = za_terr$labnr)

terr_bins <- binPrep(za_terr$Site, ages = za_terr_cal, h = 250)

# filter by marine material and apply marien curve and offset
za_marine <- za |>
  filter(material %in% c('Marine shell', 'marine shell',
                         'marine other')) |>
  drop_na(c14age, c14std)

za_marine_cal <- rcarbon::calibrate(za_marine$c14age, 
                                    za_marine$c14std,
                                    calCurves = rep('marine20',
                                                    length(za_marine$labnr)),
                                    resOffset = rep(187, length(za_marine$labnr)),
                                    resErrors = rep(18, length(za_marine$labnr)),
                                    ids = za_marine$labnr)

marine_bins <- binPrep(za_marine$Site, ages = za_marine_cal, h = 250)

# combine data
za_cal <- rcarbon::combine(za_terr_cal, za_marine_cal)
```

```{r}
time_range =  c(max_age, min_age)
time_range_df = data.frame(calBP = max_age:min_age)



za_cal_site <- za_cal |>
  as_tibble()

# Need to sample sites and dates, then combine
za_spd_df <- tibble(site = character(),
                    calBP = numeric(),
                    PrDens = numeric())

for(i in unique(za$labnr)){
  

    
    
    tmp_site <- za |>
      filter(labnr == i) |>
      select(Site)
    
    tmp_za <- za |>
      filter(Site == tmp_site$Site)
    
    
    za_terr <- tmp_za |>
      filter(!material %in% c('Marine shell', 'marine shell',
                              'marine other', 'iron')) |>
      drop_na(c14age, c14std)
    
    if(dim(za_terr)[1] != 0){
    
    za_terr_cal <- rcarbon::calibrate(za_terr$c14age , za_terr$c14std,
                                      calCurves = 'shcal20',
                                      ids = za_terr$labnr,
                                      verbose = FALSE)
    
    }
    
    # filter by marine material and apply marien curve and offset
    za_marine <- tmp_za |>
      filter(material %in% c('Marine shell', 'marine shell',
                             'marine other')) |>
      drop_na(c14age, c14std)
    if(dim(za_marine)[1] != 0){
    
      za_marine_cal <- rcarbon::calibrate(za_marine$c14age, 
                                          za_marine$c14std,
                                          calCurves = rep('marine20',
                                                          length(za_marine$labnr)),
                                          resOffset = rep(187, length(za_marine$labnr)),
                                          resErrors = rep(18, length(za_marine$labnr)),
                                          ids = za_marine$labnr,
                                          
                                          verbose = FALSE)
    }
    
    # combine data
    if((dim(za_terr)[1] == 0 & dim(za_marine)[1] != 0)){
      za_cal <- za_marine_cal
    } else if((dim(za_terr)[1] != 0 & dim(za_marine)[1] == 0)){
      za_cal <- za_terr_cal
    } else{
      za_cal <- rcarbon::combine(za_terr_cal, za_marine_cal)
    }
    
    
    target_bins = binPrep(sites = c(za_terr$Site, za_marine$Site),
                          ages = c(za_terr$c14age, za_marine$c14age), h = 100)
    
    
    tmp_spd = spd(x = za_cal,
                  bins = target_bins, 
                  timeRange = c(max_age, min_age), 
                  datenormalised = FALSE,
                  runm = 100)
    
    tmp_spd_df <- as_tibble(tmp_spd$grid)
    
    za_spd_df <- za_spd_df |>
      add_row(site = tmp_site$Site,
              calBP = tmp_spd_df$calBP,
              PrDens = tmp_spd_df$PrDens)
}
```

```{r}
site_prob <- za_spd_df |>
  mutate(
    bin = floor(calBP / temp_res) * temp_res
  ) |>
  group_by(site, bin) |>
  summarise(
    prob = sum(PrDens),
    .groups = "drop"
  ) |>
  complete(
    site = unique(za_spd_df$site),
    bin = seq(
      floor(max_age / temp_res) * temp_res,
      floor(min_age / temp_res) * temp_res,
      by = -temp_res
    ),
    fill = list(prob = 0)
  ) |>
  group_by(site) |>
  mutate(
    p = prob / sum(prob)
  ) |>
  ungroup()



dates_samp <- site_prob |>
  group_by(site) |>
  filter(sum(p) > 0) |>
  slice_sample(
    n = 1,
    weight_by = p,
    replace = TRUE
  ) |>
  ungroup() |>
  rename(calBP = bin)


iter <- 5000
seed = seed + 1
set.seed(seed)

dates_samp <- purrr::map_dfr(
  seq_len(iter),
  function(k) {
    
    site_prob |>
      group_by(site) |>
      filter(sum(p) > 0) |>
      slice_sample(
        n = 1,
        weight_by = p,
        replace = TRUE
      ) |>
      ungroup() |>
      mutate(iter = k)
    
  }
)



site_counts <- site_prob |>
  select(site, bin, p) |>
  left_join(
    dates_samp |>
      count(site, bin, name = "site_count"),
    by = c("site", "bin")
  ) |>
  mutate(
    site_count = replace_na(site_count, 0)
  )


local_lambda <- site_prob |>
  mutate(
    lambda = iter * p,
    local_rate = lambda / temp_res
  )


za_pois_all <- local_lambda |>
  mutate(
    count = rbinom(
      n(),
      size = iter,
      prob = p
    )
  ) |>
  rename(calBP = bin)
```

```{r}
za_pois_all |>
  rename(Count = count) |>
  ggplot(aes(x = calBP, y = Count, fill = Count))+
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "darkorange", high = "darkblue") +
  xlab("Calibrated Years BP")+
  theme_minimal(base_size = 8)+
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
```

```{r}
###########################################
########### ASSIGN SARD DATA ##############
za_comb <- za_pois_all |>
  rename(Site = site) |>
  left_join(za |> select(Site, lat, lon, Country, Biome, `Archaeological Period`,
                          `Archaeological Sub-chronology`, `Province or district`,
                          `Site Type`) |> distinct(Site, .keep_all = TRUE),
             by = 'Site') |>
  ungroup()


sites_sf <- st_as_sf(
  za_comb,
  coords = c("lon", "lat"),
  crs = 4326
)

sites_proj <- st_transform(
  sites_sf,
  32734
)


coords <- st_coordinates(sites_proj)

za_coords <- za_comb |>
  mutate(x = coords[,1],
         y = coords[,2])

study_area <- st_bbox(sites_proj) |>
  st_as_sfc() |>
  st_buffer(dist = 10000) |>
  vect()

###########################################
########### ASSIGN SASSI DATA ##############


sassi_sf <- st_as_sf(
  sassi,
  coords = c("Longitude", "Latitude"),
  crs = 4326
)

sassi_proj <- st_transform(
  sassi_sf,
  32734
)


sassi_coords <- st_coordinates(sassi_proj)

sassi_coords <- sassi |>
  mutate(x = sassi_coords[,1],
         y = sassi_coords[,2])

sassi_area <- st_bbox(sassi_proj) |>
  st_as_sfc() |>
  st_buffer(dist = 10000) |>
  vect()

sassi_holocene <- sassi_proj |>
  mutate(x = st_coordinates(sassi_proj)[,1],
         y = st_coordinates(sassi_proj)[,2])

africa_map <- ne_countries(scale = "medium", 
                           continent = "Africa", returnclass = "sf")


ggplot()+
  geom_sf(data = africa_map, fill = "antiquewhite", color = "darkgray") +
  geom_sf(data = sassi_holocene, aes(color = Biome)) +
  coord_sf(xlim = c(10, 42), ylim = c(-35, -10), expand = FALSE) +
  theme_minimal()
```

```{r}
za_holocene <- sites_proj |>
  mutate(x = st_coordinates(sites_proj)[,1],
         y = st_coordinates(sites_proj)[,2])

africa_map <- ne_countries(scale = "medium", 
                           continent = "Africa", returnclass = "sf")


ggplot()+
  geom_sf(data = africa_map, fill = "antiquewhite", color = "darkgray") +
  geom_sf(data = za_holocene, aes(color = `Biome`)) +
  coord_sf(xlim = c(10, 42), ylim = c(-35, -10), expand = FALSE) +
  theme_minimal()
```

```{r}
# 1. Prepare your data (using built-in multishapes dataset example)

df_tmp <- sassi_holocene[, 21:22] |>
  st_drop_geometry() |>
  distinct()


kNNdistplot(df_tmp, k = 4)
abline(h = 105000, col = "red", lty = 2)
```

```{r}
nn <- frNN(sassi_holocene |> distinct(Site, .keep_all = TRUE) |> st_coordinates(),
           eps = 105000)

hist(lengths(adjacencylist(nn)),
     xlab = "k", main="Number of Neighbors",
     sub = paste("Neighborhood size eps =", nn$eps))


min_obs <- 4


clustered_data <- sassi_holocene |>
  distinct(Site, .keep_all = TRUE) |>
  select(Site) |>
  
  mutate(cluster = {
    
    # Run DBSCAN (adjust eps and minPts to your data's scale)
    res <- dbscan(nn, minPts = min_obs)
    
    # Return cluster assignments (0 represents noise/outliers)
    res$cluster
  }) |>
  st_drop_geometry() |>
  
  full_join(sassi_holocene, by = "Site") |>
  st_sf()

clustered_data |>
  group_by(cluster) |>
  mutate(n_cluster = n()) |>
  filter(n_cluster < 15) |>
  group_by(Site, cluster, n_cluster) |>
  summarize(n_site = n()) |>
  mutate(Site_ex = ifelse((n_cluster == n_site) | (n_site < min_obs), 1, 0)) |>
  filter(Site_ex == 1) -> site_exc

#  Remove the noise cluster and clusters with too few site-specific observations
clustered_data <- clustered_data |> filter(!(cluster %in% c(0, site_exc$cluster)))


hulls_sf <- clustered_data |>
  group_by(cluster) |>
  summarize(geometry = st_combine(geometry)) |>
  st_convex_hull()

# Explore clustered data
ggplot()+
  geom_sf(data = africa_map, fill = "antiquewhite", color = "darkgray") +
  #geom_sf(data = hulls_sf, aes(fill = factor(cluster)), 
   #       alpha = 0.2, color = "black", size = 0.5) +
  geom_sf(data = clustered_data, aes(color = factor(cluster), 
                                     fill = factor(cluster))) +
  geom_mark_hull(alpha = 0.2, expand = unit(3, "mm")) +
  coord_sf(xlim = c(10, 42), ylim = c(-35, -10), expand = FALSE) +
  theme_minimal()
```

# Hierarchical Modeling

```{r}
# combine clustered data from SASSI to the SARD database
df_tmp <- za_holocene |>
  st_drop_geometry() |>
  full_join(clustered_data |> 
               st_drop_geometry() |> 
               select(Site, cluster) |>
               distinct(), by = "Site") |>
  filter(!is.na(cluster))


fit_df <- df_tmp |>
  rename(site_count = count) |>
  group_by(cluster, calBP) |>
  mutate(cluster_dates = n()) |>
  ungroup() |>
  
  mutate(time_s = as.numeric(scale(calBP)),
         time_red = calBP/1000,
         time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000,
         
         cluster_fct = factor(cluster),
         cluster_num = as.numeric(cluster),
         cluster_cat = ifelse(cluster %in% c(9, 2), 'Northwest Coast',
                    ifelse(cluster %in% c(8, 7, 6), 'Northeast',
                    ifelse(cluster %in% c(5), 'Interior-Karoo',
                    ifelse(cluster %in% c(3), 'Interior-Grassland',
                    ifelse(cluster == 4, 'East Coast', 'Southern Coast'))))),
         
         iter = iter)
```

```{r}
fit_df |>
  st_drop_geometry() |>
  
  group_by(cluster_fct) |>
  distinct(Site) |>
  summarize(count = n())


fit_df |>
  ggplot(aes(x = calBP, y = site_count, fill = site_count))+
  geom_bar(stat = "identity") +
  facet_wrap(~cluster, scale = "free") +
  scale_fill_gradient(low = "darkorange", high = "darkblue") +
  xlab("Calibrated Years BP")+
  theme_minimal(base_size = 8)+
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))


fit_df |>
  ggplot(aes(x = calBP, y = site_count, fill = site_count))+
  geom_bar(stat = "identity") +
  facet_wrap(~cluster_cat, scale = "free") +
  scale_fill_gradient(low = "darkorange", high = "darkblue") +
  xlab("Calibrated Years BP")+
  theme_minimal(base_size = 8)+
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
```

## Bayesian Modeling

```{r}
# this model shows cluster show almost no variation after accounting for mean site count
seed <- seed + 1
fit_time <- brm(
  site_count ~
    1 + time_ka,
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.98
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)

#######################################################

seed <- seed + 1
fit_space_h2 <- brm(
  site_count ~
    1 + time_ka + (0 + time_ka || cluster_fct),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)

############################################################
seed <- seed + 1
fit_space_h3 <- brm(
  site_count ~
    1 + time_ka + (0 + time_ka || cluster_cat),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)
```

```{r}
# compute posterior slope estimates for each cluster
cluster_slope_draws <- spread_draws(
  fit_space_h2,
  r_cluster_fct[cluster_fct, time_ka]
)


cluster_slope_summary <- cluster_slope_draws |>
  group_by(cluster_fct) |>
  summarise(
    estimate = median(r_cluster_fct),
    lower = quantile(r_cluster_fct, 0.025),
    upper = quantile(r_cluster_fct, 0.975),
    .groups = "drop"
  )




draws <- as_draws_df(fit_space_h2)

slope_draws <- draws |>
  select(
    .draw,
    b_time_ka,
    starts_with("r_cluster_fct[")
    ) |>
  pivot_longer(
    cols = starts_with("r_cluster_fct["),
    names_to = "cluster",
    values_to = "slope_deviation"
    ) |>
  mutate(
    cluster_slope = b_time_ka + slope_deviation,
    cluster = str_extract(cluster, "(?<=\\[)[^,]+")
    ) |>
  group_by(cluster) |>
  summarise(
    slope = median(cluster_slope),
    lower = quantile(cluster_slope, 0.025),
    upper = quantile(cluster_slope, 0.975),
    
    rate_ratio_1ka = exp(slope),
    rate_lower = exp(lower),
    rate_upper = exp(upper),
    
    .groups = "drop"
    )

slope_draws

##############################################################
##############################################################
##############################################################

# compute posterior slope estimates for each cluster
cluster_slope_draws <- spread_draws(
  fit_space_h3,
  r_cluster_cat[cluster_cat, time_ka]
)


cluster_slope_summary <- cluster_slope_draws |>
  group_by(cluster_cat) |>
  summarise(
    estimate = median(r_cluster_cat),
    lower = quantile(r_cluster_cat, 0.025),
    upper = quantile(r_cluster_cat, 0.975),
    .groups = "drop"
  )




draws <- as_draws_df(fit_space_h3)

slope_draws <- draws |>
  select(
    .draw,
    b_time_ka,
    starts_with("r_cluster_cat[")
  ) |>
  pivot_longer(
    cols = starts_with("r_cluster_cat["),
    names_to = "cluster",
    values_to = "slope_deviation"
  ) |>
  mutate(
    cluster_slope = b_time_ka + slope_deviation,
    cluster = str_extract(cluster, "(?<=\\[)[^,]+")
  ) |>
  group_by(cluster) |>
  summarise(
    slope = median(cluster_slope),
    lower = quantile(cluster_slope, 0.025),
    upper = quantile(cluster_slope, 0.975),
    
    rate_ratio_1ka = exp(slope),
    rate_lower = exp(lower),
    rate_upper = exp(upper),
    
    .groups = "drop"
  )

slope_draws
```

```{r}
# slope comparisons
slope_draws <- as.data.frame(
  coef(fit_space_h2, summary = FALSE)$cluster_fct
)

colnames(slope_draws) <- paste0(
  "cluster_", seq_len(ncol(slope_draws))
)

slope_pairs <- combn(
  colnames(slope_draws),
  2,
  simplify = FALSE
)

pairwise_slopes <- map_dfr(
  slope_pairs,
  \(x) {
    
    diff <- slope_draws[[x[1]]] - slope_draws[[x[2]]]
    
    tibble(
      cluster_1 = x[1],
      cluster_2 = x[2],
      difference = diff,
      estimate = median(diff),
      lower = quantile(diff, 0.025),
      upper = quantile(diff, 0.975),
      prob_cluster1_greater = mean(diff > 0)
    )
  }
)

# shows that no slopes are actually significantly different
pairwise_slopes |> 
  distinct(lower, upper, .keep_all = TRUE) |>
  filter((lower < 0 & upper < 0) | (lower > 0 & upper > 0))
  
###############################################################################
###############################################################################
###############################################################################
  
  # slope comparisons
  slope_draws <- as.data.frame(
    coef(fit_space_h3, summary = FALSE)$cluster_cat
  )

  slope_pairs <- combn(
    colnames(slope_draws),
    2,
    simplify = FALSE
  )
  
  pairwise_slopes <- map_dfr(
    slope_pairs,
    \(x) {
      
      diff <- slope_draws[[x[1]]] - slope_draws[[x[2]]]
      
      tibble(
        cluster_1 = x[1],
        cluster_2 = x[2],
        difference = diff,
        estimate = median(diff),
        lower = quantile(diff, 0.025),
        upper = quantile(diff, 0.975),
        prob_cluster1_greater = mean(diff > 0)
      )
    }
  )
  
  # shows that no slopes are actually significantly different
  pairwise_slopes |> 
    distinct(lower, upper, .keep_all = TRUE) |>
  filter(prob_cluster1_greater <= 0.1 | prob_cluster1_greater >= 0.9,
         str_detect(cluster_1, 'ka') & str_detect(cluster_2, 'ka'))
```

```{r}
# compare at different points in time
prediction_grid <- expand_grid(
  calBP = seq(min_age, max_age, by = 1000),
  cluster_fct = unique(fit_df$cluster_fct)
) |>
  mutate(time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000)


pred <- fitted(
  fit_space_h2,
  newdata = prediction_grid,
  re_formula = NULL,
  summary = TRUE,
  allow_new_levels = TRUE
)

prediction_grid <- prediction_grid |>
  bind_cols(
    as.data.frame(pred)
  )


prediction_grid |>
  filter(
    calBP == 12000,
    cluster_fct %in% c("3", "5")
  )

ggplot(
  prediction_grid |> filter(calBP > 10000),
  aes(
    x = calBP,
    y = Estimate,
    group = cluster_fct,
    colour = cluster_fct
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = cluster_fct
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Expected site occurrence",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()


######################################################
######################################################

# compare at different points in time
prediction_grid <- expand_grid(
  calBP = seq(min_age, max_age, by = 1000),
  cluster_cat = unique(fit_df$cluster_cat)
) |>
  mutate(time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000)


pred <- fitted(
  fit_space_h3,
  newdata = prediction_grid,
  re_formula = NULL,
  summary = TRUE
)

prediction_grid <- prediction_grid |>
  bind_cols(
    as.data.frame(pred)
  )


prediction_grid |>
  filter(
    calBP == 12000,
    cluster_cat %in% c("Southern Coastal", "Interior")
  )



ggplot(
  prediction_grid |> 
    filter(cluster_cat %in% c('Southern Coast', 'Interior-Karoo', 'Northeast')),
  aes(
    x = calBP,
    y = Estimate,
    group = cluster_cat,
    colour = cluster_cat
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = cluster_cat
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Radiocarbon Intensity",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()



ggplot(
  prediction_grid |> 
    filter(cluster_cat %in% c('Southern Coast', 'Interior-Karoo', 'Northeast'),
           calBP > 9000),
  aes(
    x = calBP,
    y = Estimate,
    group = cluster_cat,
    colour = cluster_cat
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = cluster_cat
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Radiocarbon Intensity",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()
```

```{r}
# COompare age ranges
intervals <- tribble(
  ~period, ~start, ~end,
  "18–12 ka", 12000, 18000,
  "12–8 ka", 8000, 12000,
  "8–4 ka",   4000, 8000,
  "4–2 ka",    2000,  4000
)

interval_grid <- crossing(
  intervals,
  cluster_fct = levels(fit_df$cluster_fct),
  calBP = seq(2000, 18000, by = 500)
) |>
  filter(
    calBP >= pmin(start, end),
    calBP <= pmax(start, end)
  ) |>
  mutate(
    time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000
  )

interval_pred <- posterior_epred(
  fit_space_h2,
  newdata = interval_grid,
  re_formula = NULL,
  allow_new_levels = TRUE
)


pred_long <- interval_grid |>
  select(period, cluster_fct, calBP) |>
  bind_cols(
    as.data.frame(t(interval_pred))
  ) |>
  pivot_longer(
    cols = starts_with("V"),
    names_to = "draw",
    values_to = "mu"
  )

# caculate expectations
interval_summary <- pred_long |>
  group_by(period, cluster_fct, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  ) |>
  group_by(period, cluster_fct) |>
  summarise(
    estimate = median(mean_count),
    lower = quantile(mean_count, 0.025),
    upper = quantile(mean_count, 0.975),
    .groups = "drop"
  )


interval_summary |>
  mutate(period = fct_relevel(period,
                              "18–12 ka", "12–8 ka", "8–4 ka", "4–2 ka")) |>
  
  ggplot(aes(x = cluster_fct, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.15
  ) +
  facet_grid(~period, scales = "free_y") +
  ylab("Expected radiocarbon date values") +
  theme_minimal()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
###################################################
###################################################
###################################################
interval_grid <- crossing(
  intervals,
  cluster_cat = unique(fit_df$cluster_cat),
  calBP = seq(2000, 18000, by = 500)
) |>
  filter(
    calBP >= pmin(start, end),
    calBP <= pmax(start, end)
  ) |>
  mutate(
    time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000
  )

interval_pred <- posterior_epred(
  fit_space_h3,
  newdata = interval_grid,
  re_formula = NULL
)


pred_long <- interval_grid |>
  select(period, cluster_cat, calBP) |>
  bind_cols(
    as.data.frame(t(interval_pred))
  ) |>
  pivot_longer(
    cols = starts_with("V"),
    names_to = "draw",
    values_to = "mu"
  )

# caculate expectations
interval_summary <- pred_long |>
  group_by(period, cluster_cat, draw) |>
  mutate(period = as.factor(period)) |> 
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  ) |>
  group_by(period, cluster_cat) |>
  summarise(
    estimate = median(mean_count),
    lower = quantile(mean_count, 0.025),
    upper = quantile(mean_count, 0.975),
    .groups = "drop"
  )

interval_summary |>
  mutate(period = fct_relevel(period,
                              "18–12 ka", "12–8 ka", "8–4 ka", "4–2 ka")) |>
      
  ggplot(aes(x = cluster_cat, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.15
  ) +
  facet_wrap(~period, scales = "free_y") +
  ylab("Radiocarbon Intensity") +
  theme_minimal()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
```

### Interval rate ratio

```{r}
interval_draws <- pred_long |>
  group_by(period, cluster_fct, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  )

clusters <- unique(interval_draws$cluster_fct)

cluster_pairs <- combn(
  clusters,
  2,
  simplify = FALSE
)

interval_rate_ratios <- map_dfr(
  cluster_pairs,
  \(pair) {
    
    a <- interval_draws |>
      filter(cluster_fct == pair[1]) |>
      select(period, draw, count_a = mean_count)
    
    b <- interval_draws |>
      filter(cluster_fct == pair[2]) |>
      select(period, draw, count_b = mean_count)
    
    left_join(a, b, by = c("period", "draw")) |>
      mutate(
        cluster_1 = pair[1],
        cluster_2 = pair[2],
        rate_ratio = count_a / count_b
      )
  }
)


interval_rate_ratio_summary <- interval_rate_ratios |>
  group_by(period, cluster_1, cluster_2) |>
  summarise(
    estimate = median(rate_ratio),
    lower = quantile(rate_ratio, 0.025),
    upper = quantile(rate_ratio, 0.975),
    prob_greater_1 = mean(rate_ratio > 1),
    .groups = "drop"
  )

interval_rate_ratio_summary |>
  filter(prob_greater_1 > 0.9 | prob_greater_1 < 0.1)


####################################################################
####################################################################
####################################################################
interval_draws <- pred_long |>
  group_by(period, cluster_cat, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  )

clusters <- unique(interval_draws$cluster_cat)

cluster_pairs <- combn(
  clusters,
  2,
  simplify = FALSE
)

interval_rate_ratios <- map_dfr(
  cluster_pairs,
  \(pair) {
    
    a <- interval_draws |>
      filter(cluster_cat == pair[1]) |>
      select(period, draw, count_a = mean_count)
    
    b <- interval_draws |>
      filter(cluster_cat == pair[2]) |>
      select(period, draw, count_b = mean_count)
    
    left_join(a, b, by = c("period", "draw")) |>
      mutate(
        cluster_1 = pair[1],
        cluster_2 = pair[2],
        rate_ratio = count_a / count_b
      )
  }
)


interval_rate_ratio_summary <- interval_rate_ratios |>
  group_by(period, cluster_1, cluster_2) |>
  summarise(
    estimate = median(rate_ratio),
    lower = quantile(rate_ratio, 0.05),
    upper = quantile(rate_ratio, 0.95),
    prob_greater_1 = mean(rate_ratio > 1),
    .groups = "drop"
  )

interval_rate_ratio_summary |>
  filter(prob_greater_1 > 0.90 | prob_greater_1 < 0.10)
```

### Within cluster change

```{r}
# temporal change within each cluster
temporal_change <- interval_draws |>
  #filter(period %in% c("18–12 ka", "12–8 ka", "8-4 ka", "4-2 ka")) |>
  select(cluster_fct, period, draw, mean_count) |>
  pivot_wider(
    names_from = period,
    values_from = mean_count
  ) |>
  mutate(
    rate_ratio_Rob_Oak = `12–8 ka` / `18–12 ka`,
    rate_ratio_Oak_Wilt = `8–4 ka` / `12–8 ka`,
    rate_ratio_Wilt_Post = `4–2 ka` / `8–4 ka`
  ) 



temporal_change |>
  pivot_longer('12–8 ka':'rate_ratio_Wilt_Post', 
               names_to = 'Rates', values_to = 'Pred') |>
  group_by(Rates) |>
  summarise(
    estimate = round(median(Pred), 3),
    lower = round(quantile(Pred, 0.025), 3),
    upper = round(quantile(Pred, 0.975), 3),
    .groups = "drop"
  )


###########################################################
###########################################################
###########################################################

# temporal change within each cluster
temporal_change <- interval_draws |>
  #filter(period %in% c("18–12 ka", "12–8 ka", "8-4 ka", "4-2 ka")) |>
  select(cluster_cat, period, draw, mean_count) |>
  pivot_wider(
    names_from = period,
    values_from = mean_count
  ) |>
  mutate(
    rate_ratio_Rob_Oak = `12–8 ka` / `18–12 ka`,
    rate_ratio_Oak_Wilt = `8–4 ka` / `12–8 ka`,
    rate_ratio_Wilt_Post = `4–2 ka` / `8–4 ka`
  ) 



temporal_change |>
  pivot_longer('12–8 ka':'rate_ratio_Wilt_Post', 
               names_to = 'Rates', values_to = 'Pred') |>
  group_by(Rates) |>
  summarise(
    estimate = round(median(Pred), 3),
    lower = round(quantile(Pred, 0.025), 3),
    upper = round(quantile(Pred, 0.975), 3),
    .groups = "drop"
  )

```

# Biome modeling

```{r}
# combine clustered data from SASSI to the SARD database
df_tmp <- za_holocene |>
  st_drop_geometry() |>
  full_join(clustered_data |> 
               st_drop_geometry() |> 
               select(Site, cluster) |>
               distinct(), by = "Site") |>
  filter(!is.na(cluster))


fit_df <- df_tmp |>
  rename(site_count = count,
         Site_Type = `Site Type`) |>
  group_by(cluster, calBP) |>
  mutate(cluster_dates = n()) |>
  ungroup() |>
  
  mutate(time_s = as.numeric(scale(calBP)),
         time_red = calBP/1000,
         time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000,
         
         cluster_fct = factor(cluster),
         cluster_num = as.numeric(cluster),
         cluster_cat = ifelse(cluster %in% c(9, 2), 'Northwest Coast',
                    ifelse(cluster %in% c(8, 7, 6), 'Northeast',
                    ifelse(cluster %in% c(5), 'Interior-Karoo',
                    ifelse(cluster %in% c(3), 'Interior-Grassland',
                    ifelse(cluster == 4, 'East Coast', 'Southern Coast'))))),
         
         Site_Type = as.factor(Site_Type),
         
         iter = iter)
```

```{r}
fit_df |>
  st_drop_geometry() |>
  
  group_by(cluster_fct) |>
  distinct(Site) |>
  summarize(count = n())


fit_df |>
  ggplot(aes(x = calBP, y = site_count, fill = site_count))+
  geom_bar(stat = "identity") +
  facet_wrap(~Biome, scale = "free") +
  scale_fill_gradient(low = "darkorange", high = "darkblue") +
  xlab("Calibrated Years BP")+
  theme_minimal(base_size = 8)+
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))


fit_df |>
  ggplot(aes(x = calBP, y = site_count, fill = site_count))+
  geom_bar(stat = "identity") +
  facet_wrap(~Site_Type, scale = "free") +
  scale_fill_gradient(low = "darkorange", high = "darkblue") +
  xlab("Calibrated Years BP")+
  theme_minimal(base_size = 8)+
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
```

## Bayesian Modeling

```{r}
# this model shows cluster show almost no variation after accounting for mean site count
seed <- seed + 1
fit_time <- brm(
  site_count ~
    1 + time_ka,
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.98
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)

#######################################################

seed <- seed + 1
fit_space_biome <- brm(
  site_count ~
    1 + time_ka + (0 + time_ka || Biome),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)

############################################################
seed <- seed + 1
fit_space_site_type <- brm(
  site_count ~
    1 + time_ka + (0 + time_ka || Site_Type),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)
```

```{r}
# compute posterior slope estimates for each cluster
cluster_slope_draws <- spread_draws(
  fit_space_biome,
  r_Biome[Biome, time_ka]
)


cluster_slope_summary <- cluster_slope_draws |>
  group_by(Biome) |>
  summarise(
    estimate = median(r_Biome),
    lower = quantile(r_Biome, 0.05),
    upper = quantile(r_Biome, 0.95),
    .groups = "drop"
  )




draws <- as_draws_df(fit_space_biome)

slope_draws <- draws |>
  select(
    .draw,
    b_time_ka,
    starts_with("r_Biome[")
    ) |>
  pivot_longer(
    cols = starts_with("r_Biome["),
    names_to = "biome",
    values_to = "slope_deviation"
    ) |>
  mutate(
    biome_slope = b_time_ka + slope_deviation,
    biome = str_extract(biome, "(?<=\\[)[^,]+")
    ) |>
  group_by(biome) |>
  summarise(
    slope = median(biome_slope),
    lower = quantile(biome_slope, 0.05),
    upper = quantile(biome_slope, 0.95),
    
    rate_ratio_1ka = exp(slope),
    rate_lower = exp(lower),
    rate_upper = exp(upper),
    
    .groups = "drop"
    )

slope_draws

##############################################################
##############################################################
##############################################################

# compute posterior slope estimates for each cluster
cluster_slope_draws <- spread_draws(
  fit_space_site_type,
  r_Site_Type[Site_Type, time_ka]
)


cluster_slope_summary <- cluster_slope_draws |>
  group_by(Site_Type) |>
  summarise(
    estimate = median(r_Site_Type),
    lower = quantile(r_Site_Type, 0.025),
    upper = quantile(r_Site_Type, 0.975),
    .groups = "drop"
  )




draws <- as_draws_df(fit_space_site_type)

slope_draws <- draws |>
  select(
    .draw,
    b_time_ka,
    starts_with("r_Site_Type[")
  ) |>
  pivot_longer(
    cols = starts_with("r_Site_Type["),
    names_to = "site_type",
    values_to = "slope_deviation"
  ) |>
  mutate(
    site_type_slope = b_time_ka + slope_deviation,
    site_type = str_extract(site_type, "(?<=\\[)[^,]+")
  ) |>
  group_by(site_type) |>
  summarise(
    slope = median(site_type_slope),
    lower = quantile(site_type_slope, 0.025),
    upper = quantile(site_type_slope, 0.975),
    
    rate_ratio_1ka = exp(slope),
    rate_lower = exp(lower),
    rate_upper = exp(upper),
    
    .groups = "drop"
  )

slope_draws
```

```{r}
# slope comparisons
slope_draws <- as.data.frame(
  coef(fit_space_biome, summary = FALSE)$Biome
)

slope_pairs <- combn(
  colnames(slope_draws),
  2,
  simplify = FALSE
)

pairwise_slopes <- map_dfr(
  slope_pairs,
  \(x) {
    
    diff <- slope_draws[[x[1]]] - slope_draws[[x[2]]]
    
    tibble(
      Biome_1 = x[1],
      Biome_2 = x[2],
      difference = diff,
      estimate = median(diff),
      lower = quantile(diff, 0.025),
      upper = quantile(diff, 0.975),
      prob_biome1_greater = mean(diff > 0)
    )
  }
)

# shows that no slopes are actually significantly different
pairwise_slopes |> 
  distinct(lower, upper, .keep_all = TRUE) |>
  filter((lower < 0 & upper < 0) | (lower > 0 & upper > 0),
         str_detect(Biome_1, 'ka') & str_detect(Biome_2, 'ka'))
  
###############################################################################
###############################################################################
###############################################################################
  
  # slope comparisons
  slope_draws <- as.data.frame(
    coef(fit_space_site_type, summary = FALSE)$Site_Type
  )

  slope_pairs <- combn(
    colnames(slope_draws),
    2,
    simplify = FALSE
  )
  
  pairwise_slopes <- map_dfr(
    slope_pairs,
    \(x) {
      
      diff <- slope_draws[[x[1]]] - slope_draws[[x[2]]]
      
      tibble(
        siteType_1 = x[1],
        siteType_2 = x[2],
        difference = diff,
        estimate = median(diff),
        lower = quantile(diff, 0.05),
        upper = quantile(diff, 0.95),
        prob_siteType1_greater = mean(diff > 0)
      )
    }
  )
  
  # shows that no slopes are actually significantly different
  pairwise_slopes |> 
    distinct(lower, upper, .keep_all = TRUE) |>
  filter(prob_siteType1_greater <= 0.1 | prob_siteType1_greater >= 0.9,
         str_detect(siteType_1, 'ka') & str_detect(siteType_2, 'ka'))
```

```{r}
# compare at different points in time
prediction_grid <- expand_grid(
  calBP = seq(min_age, max_age, by = 1000),
  Biome = unique(fit_df$Biome)
) |>
  mutate(time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000)


pred <- fitted(
  fit_space_biome,
  newdata = prediction_grid,
  re_formula = NULL,
  summary = TRUE,
  allow_new_levels = TRUE
)

prediction_grid <- prediction_grid |>
  bind_cols(
    as.data.frame(pred)
  )


#prediction_grid |> filter(calBP == 12000,cluster_fct %in% c("3", "5") )

ggplot(
  prediction_grid |> filter(calBP > 12000, !is.na(Biome)),
  aes(
    x = calBP,
    y = Estimate,
    group = Biome,
    colour = Biome
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = Biome
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Expected site occurrence",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()


######################################################
######################################################

# compare at different points in time
prediction_grid <- expand_grid(
  calBP = seq(min_age, max_age, by = 1000),
  cluster_cat = unique(fit_df$cluster_cat)
) |>
  mutate(time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000)


pred <- fitted(
  fit_space_h3,
  newdata = prediction_grid,
  re_formula = NULL,
  summary = TRUE
)

prediction_grid <- prediction_grid |>
  bind_cols(
    as.data.frame(pred)
  )


prediction_grid |>
  filter(
    calBP == 12000,
    cluster_cat %in% c("Southern Coastal", "Interior")
  )



ggplot(
  prediction_grid |> 
    filter(cluster_cat %in% c('Southern Coast', 'Interior-Karoo', 'Northeast')),
  aes(
    x = calBP,
    y = Estimate,
    group = cluster_cat,
    colour = cluster_cat
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = cluster_cat
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Radiocarbon Intensity",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()



ggplot(
  prediction_grid |> 
    filter(cluster_cat %in% c('Southern Coast', 'Interior-Karoo', 'Northeast'),
           calBP > 9000),
  aes(
    x = calBP,
    y = Estimate,
    group = cluster_cat,
    colour = cluster_cat
  )
) +
  geom_ribbon(
    aes(
      ymin = Q2.5,
      ymax = Q97.5,
      fill = cluster_cat
    ),
    alpha = 0.15,
    colour = NA
  ) +
  geom_line(linewidth = 1) +
  scale_x_reverse() +
  labs(
    x = "Calendar age (cal BP)",
    y = "Radiocarbon Intensity",
    colour = "Cluster",
    fill = "Cluster"
  ) +
  theme_classic()
```

```{r}
# COompare age ranges
intervals <- tribble(
  ~period, ~start, ~end,
  "18–12 ka", 12000, 18000,
  "12–8 ka", 8000, 12000,
  "8–4 ka",   4000, 8000,
  "4–2 ka",    2000,  4000
)

interval_grid <- crossing(
  intervals,
  Biome = unique(fit_df$Biome),
  calBP = seq(2000, 18000, by = 500)
) |>
  filter(
    calBP >= pmin(start, end),
    calBP <= pmax(start, end)
  ) |>
  mutate(
    time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000
  )

interval_pred <- posterior_epred(
  fit_space_biome,
  newdata = interval_grid,
  re_formula = NULL,
  allow_new_levels = TRUE
)


pred_long <- interval_grid |>
  select(period, Biome, calBP) |>
  bind_cols(
    as.data.frame(t(interval_pred))
  ) |>
  pivot_longer(
    cols = starts_with("V"),
    names_to = "draw",
    values_to = "mu"
  )

# caculate expectations
interval_summary <- pred_long |>
  group_by(period, Biome, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  ) |>
  group_by(period, Biome) |>
  summarise(
    estimate = median(mean_count),
    lower = quantile(mean_count, 0.05),
    upper = quantile(mean_count, 0.95),
    .groups = "drop"
  ) |>
  filter(!is.na(Biome))


interval_summary |>
  mutate(period = fct_relevel(period,
                              "18–12 ka", "12–8 ka", "8–4 ka", "4–2 ka")) |>
  
  ggplot(aes(x = Biome, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.15
  ) +
  facet_wrap(~period, scales = "free_y") +
  ylab("Expected radiocarbon date values") +
  theme_minimal()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
###################################################
###################################################
###################################################
interval_grid <- crossing(
  intervals,
  cluster_cat = unique(fit_df$cluster_cat),
  calBP = seq(2000, 18000, by = 500)
) |>
  filter(
    calBP >= pmin(start, end),
    calBP <= pmax(start, end)
  ) |>
  mutate(
    time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000
  )

interval_pred <- posterior_epred(
  fit_space_h3,
  newdata = interval_grid,
  re_formula = NULL
)


pred_long <- interval_grid |>
  select(period, cluster_cat, calBP) |>
  bind_cols(
    as.data.frame(t(interval_pred))
  ) |>
  pivot_longer(
    cols = starts_with("V"),
    names_to = "draw",
    values_to = "mu"
  )

# caculate expectations
interval_summary <- pred_long |>
  group_by(period, cluster_cat, draw) |>
  mutate(period = as.factor(period)) |> 
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  ) |>
  group_by(period, cluster_cat) |>
  summarise(
    estimate = median(mean_count),
    lower = quantile(mean_count, 0.025),
    upper = quantile(mean_count, 0.975),
    .groups = "drop"
  )

interval_summary |>
  mutate(period = fct_relevel(period,
                              "18–12 ka", "12–8 ka", "8–4 ka", "4–2 ka")) |>
      
  ggplot(aes(x = cluster_cat, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.15
  ) +
  facet_wrap(~period, scales = "free_y") +
  ylab("Radiocarbon Intensity") +
  theme_minimal()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
```

### Interval rate ratio

```{r}
interval_draws <- pred_long |>
  group_by(period, Biome, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  ) |>
  filter(!is.na(Biome))

biome <- unique(interval_draws$Biome)

biome_pairs <- combn(
  biome,
  2,
  simplify = FALSE
)

interval_rate_ratios <- map_dfr(
  biome_pairs,
  \(pair) {
    
    a <- interval_draws |>
      filter(Biome == pair[1]) |>
      select(period, draw, count_a = mean_count)
    
    b <- interval_draws |>
      filter(Biome == pair[2]) |>
      select(period, draw, count_b = mean_count)
    
    left_join(a, b, by = c("period", "draw")) |>
      mutate(
        biome_1 = pair[1],
        biome_2 = pair[2],
        rate_ratio = count_a / count_b
      )
  }
)


interval_rate_ratio_summary <- interval_rate_ratios |>
  group_by(period, biome_1, biome_2) |>
  summarise(
    estimate = median(rate_ratio),
    lower = quantile(rate_ratio, 0.05),
    upper = quantile(rate_ratio, 0.95),
    prob_greater_1 = mean(rate_ratio > 1),
    .groups = "drop"
  )

interval_rate_ratio_summary |>
  filter(prob_greater_1 > 0.9 | prob_greater_1 < 0.1)


####################################################################
####################################################################
####################################################################
interval_draws <- pred_long |>
  group_by(period, cluster_cat, draw) |>
  summarise(
    mean_count = mean(mu),
    .groups = "drop"
  )

clusters <- unique(interval_draws$cluster_cat)

cluster_pairs <- combn(
  clusters,
  2,
  simplify = FALSE
)

interval_rate_ratios <- map_dfr(
  cluster_pairs,
  \(pair) {
    
    a <- interval_draws |>
      filter(cluster_cat == pair[1]) |>
      select(period, draw, count_a = mean_count)
    
    b <- interval_draws |>
      filter(cluster_cat == pair[2]) |>
      select(period, draw, count_b = mean_count)
    
    left_join(a, b, by = c("period", "draw")) |>
      mutate(
        cluster_1 = pair[1],
        cluster_2 = pair[2],
        rate_ratio = count_a / count_b
      )
  }
)


interval_rate_ratio_summary <- interval_rate_ratios |>
  group_by(period, cluster_1, cluster_2) |>
  summarise(
    estimate = median(rate_ratio),
    lower = quantile(rate_ratio, 0.05),
    upper = quantile(rate_ratio, 0.95),
    prob_greater_1 = mean(rate_ratio > 1),
    .groups = "drop"
  )

interval_rate_ratio_summary |>
  filter(prob_greater_1 > 0.90 | prob_greater_1 < 0.10)
```

# Spatiotemporal

```{r}
fit_df <- za_holocene |>
  rename(site_count = count,
         Site_Type = `Site Type`) |>
  
  mutate(time_red = calBP/1000,
         time_ka = (calBP - mean(calBP, na.rm = TRUE))/1000,
         time_s = as.numeric(scale(calBP, center = TRUE, scale = TRUE)),
         
         lat_s = as.numeric(scale(y), center = TRUE, scale = TRUE),
         lon_s = as.numeric(scale(x), center = TRUE, scale = TRUE),
         
         Site_Type = as.factor(Site_Type),
         
         iter = iter) |>
  filter(!is.na(lat_s) & !is.na(lon_s))
```

```{r}

#seed <- seed + 1
seed <- 28
fit_spatiotemporal <- brm(
  site_count ~
    1 +
    time_s +
    gp(lon_s, lat_s),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)

#seed <- seed + 1
seed <- 29
fit_spatiotemporal2 <- brm(
  site_count ~
    1 +
    time_s +
    gp(lon_s, lat_s) +
    gp(lon_s, lat_s, by = time_s),
  
  family = negbinomial(),
  
  data = fit_df,
  
  prior = c(
    prior(normal(0, 2), class = "Intercept")
  ),
  
  chains = 1,
  iter = 4000,
  warmup = 2000,
  
  control = list(
    adapt_delta = 0.95
  ),
  
  cores = 4,
  threads = threading(8),
  backend = 'cmdstanr',
  seed = seed
)
```

```{r}
lon_center <- mean(fit_df$x)
lon_scale  <- sd(fit_df$x)

lat_center <- mean(fit_df$y)
lat_scale  <- sd(fit_df$y)

time_center <- mean(fit_df$calBP)
time_scale  <- sd(fit_df$calBP)


prediction_grid <- expand_grid(
  lon_s = seq(min(fit_df$lon_s), max(fit_df$lon_s),
              length.out = 20),
  lat_s = seq(min(fit_df$lat_s), max(fit_df$lat_s),
              length.out = 20),
  time_s = seq(min(fit_df$time_s), max(fit_df$time_s),
               length.out = 10),
) |>
  mutate(
    lon = (lon_s * lon_scale) + lon_center,
    lat = (lat_s * lat_scale) + lat_center,
    
    calBP = time_s * time_scale + time_center
  )

prediction_sf <- st_as_sf(
  prediction_grid,
  coords = c("lon", "lat"),
  crs = 4326,
  remove = FALSE)

xy <- st_coordinates(prediction_sf)

prediction_grid <- prediction_sf |>
  st_drop_geometry() |>
  mutate(
    x = xy[, 1],
    y = xy[, 2]
  )

post_pred <- posterior_epred(
  fit_spatiotemporal,
  newdata = prediction_grid,
  re_formula = NA
)

prediction_grid <- prediction_grid |>
  mutate(
    estimate = apply(post_pred, 2, median),
    lower = apply(post_pred, 2, quantile, probs = 0.05),
    upper = apply(post_pred, 2, quantile, probs = 0.95)
  )
```

```{r}
southern_africa_utm <- st_transform(
  africa_map,
  crs = 32735   # replace with the UTM CRS you're using
)


ggplot() +
  
  geom_raster(data = prediction_grid |> 
                filter(calBP == 2000) |> 
                mutate(estimate = as.numeric(log(estimate))),
              aes(x = lon, y = lat, fill = estimate)) +
  
  geom_sf(
    data = southern_africa_utm,
    fill = NA,
    color = "black",
    linewidth = 0.4
  )  +
  
  scale_fill_viridis_c() +
  coord_sf(expand = FALSE) +
  theme_minimal()

ggplot() +
  geom_sf(
    data = southern_africa_utm,
    fill = NA,
    color = "black",
    linewidth = 0.4
  ) +
  geom_sf(data = za_holocene, aes(color = `Biome`)) +
  scale_fill_viridis_c()

ggplot() +
  geom_sf(data = southern_africa_utm, fill = "grey90", color = "grey40")+
  coord_sf(xlim = c(min(za_holocene$x), max(za_holocene$x)), ylim = c(min(za_holocene$y), max(za_holocene$y)), expand = FALSE) +
  theme_minimal()
```

```{r}
pred_summary <- pred_long |>
  group_by(lon, lat, calBP) |>
  summarise(
    estimate = median(radiocarbon_rate),
    lower = quantile(radiocarbon_rate, 0.05),
    upper = quantile(radiocarbon_rate, 0.95),
    .groups = "drop"
  ) |>
  filter(!is.na(lon))


pred_sf <- st_as_sf(
  pred_summary,
  coords = c("lon", "lat"),
  crs = 32734
) |>
  st_transform(
    crs = 4326
  )

pred_coord <- pred_sf |>
  mutate(
    lon = st_coordinates(pred_sf)[,1],
    lat = st_coordinates(pred_sf)[,2]
  ) 


ggplot()+
  geom_sf(data = pred_coord, aes(x = lon, y = lat))


ggplot() +
  geom_sf(data = africa_map, fill = "grey90", color = "grey40") +
  
  geom_raster(data = pred_coord, aes(x = lon, y = lat, fill = estimate)) 
  
  coord_sf() +
  scale_fill_viridis_c() +
  theme_minimal()
```

```{r}
interp_surface <- interp(x = pred_coord$lon, y = pred_coord$lat, 
                        z = pred_coord$estimate, duplicate = 'mean')

surface_df <- expand.grid(
  lon = interp_surface$x,
  lat = interp_surface$y
) |>
  mutate(estimate = as.vector(interp_surface$z))

ggplot() +
  geom_sf(data = africa_map, fill = "grey90", color = "grey40") +
  geom_raster(
    data = surface_df,
    aes(
      x = lon,
      y = lat,
      fill = estimate
    )
  ) +
  coord_sf()





# 3. Convert the interpolated matrix back to a data frame for ggplot
continuous_surface <- expand.grid(lon = spline_interp$x, lat = spline_interp$y)
continuous_surface$value <- as.vector(spline_interp$z)
continuous_surface <- na.omit(continuous_surface)


ggplot() +
  geom_sf(data = africa_map, fill = "grey90", color = "grey40")+
  geom_raster(data = continuous_surface,  aes(x = lon, y = lat, fill = value),
              interpolate = TRUE) +
  coord_sf(xlim = c(10, 42), ylim = c(-35, -10), expand = FALSE)
  
  

```

```{r}
ggplot()+
geom_sf(
  data = africa_map,
  fill = "grey90",
  color = "grey40"
)
  
  
  coord_sf(xlim = c(10, 42), ylim = c(-35, -10), expand = FALSE)
```
